//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelMateWeb.Dal.DataCore
{
    using System;
    using System.Collections.Generic;
    
    public partial class BusinessAccount
    {
        public BusinessAccount()
        {
            this.BusinessCorporateAccounts = new HashSet<BusinessCorporateAccount>();
            this.Guests = new HashSet<Guest>();
            this.SoldItemsAlls = new HashSet<SoldItemsAll>();
            this.GuestRooms = new HashSet<GuestRoom>();
            this.Payments = new HashSet<Payment>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string ContactName { get; set; }
        public string Telephone { get; set; }
        public string Mobile { get; set; }
        public string ContactNumber { get; set; }
        public string Address { get; set; }
        public string CompanyName { get; set; }
        public string CompanyAddress { get; set; }
        public string CompanyTelephone { get; set; }
        public string NatureOfBusiness { get; set; }
        public string Email { get; set; }
        public string Status { get; set; }
        public int HotelId { get; set; }
        public bool Debtor { get; set; }
        public int AccountTypeId { get; set; }
    
        public virtual Hotel Hotel { get; set; }
        public virtual ICollection<BusinessCorporateAccount> BusinessCorporateAccounts { get; set; }
        public virtual ICollection<Guest> Guests { get; set; }
        public virtual ICollection<SoldItemsAll> SoldItemsAlls { get; set; }
        public virtual ICollection<GuestRoom> GuestRooms { get; set; }
        public virtual ICollection<Payment> Payments { get; set; }
    }
}
