//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelMateWeb.Dal.DataCore
{
    using System;
    using System.Collections.Generic;
    
    public partial class DistributionPoint
    {
        public DistributionPoint()
        {
            this.Batches = new HashSet<Batch>();
            this.DamagedBatchItems = new HashSet<DamagedBatchItem>();
            this.DistributionPointItems = new HashSet<DistributionPointItem>();
            this.Payments = new HashSet<Payment>();
            this.POSItems = new HashSet<POSItem>();
            this.SoldItemsAlls = new HashSet<SoldItemsAll>();
            this.UsedItemsByHotels = new HashSet<UsedItemsByHotel>();
            this.People = new HashSet<Person>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int DistributionPointManager { get; set; }
        public bool IsSales { get; set; }
    
        public virtual ICollection<Batch> Batches { get; set; }
        public virtual ICollection<DamagedBatchItem> DamagedBatchItems { get; set; }
        public virtual ICollection<DistributionPointItem> DistributionPointItems { get; set; }
        public virtual ICollection<Payment> Payments { get; set; }
        public virtual ICollection<POSItem> POSItems { get; set; }
        public virtual ICollection<SoldItemsAll> SoldItemsAlls { get; set; }
        public virtual ICollection<UsedItemsByHotel> UsedItemsByHotels { get; set; }
        public virtual Person Person { get; set; }
        public virtual ICollection<Person> People { get; set; }
    }
}
