//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelMateWeb.Dal.DataCore
{
    using System;
    using System.Collections.Generic;
    
    public partial class DistributionPointItem
    {
        public int Id { get; set; }
        public int DistributionPointId { get; set; }
        public int ItemId { get; set; }
        public int Quantity { get; set; }
        public System.DateTime DateAdded { get; set; }
        public int RecievedBy { get; set; }
        public int Remaining { get; set; }
        public Nullable<int> BatchId { get; set; }
        public int PreviousRemaining { get; set; }
        public int Damaged { get; set; }
    
        public virtual StockItem StockItem { get; set; }
        public virtual Batch Batch { get; set; }
        public virtual DistributionPoint DistributionPoint { get; set; }
        public virtual Person Person { get; set; }
    }
}
