//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelMateWeb.Dal.DataCore
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeShift
    {
        public int Id { get; set; }
        public System.DateTime ShiftDate { get; set; }
        public System.DateTime StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public int PersonId { get; set; }
        public decimal TotalHotelSalesRecievable { get; set; }
        public decimal TotalSales { get; set; }
        public string CloseMethod { get; set; }
        public decimal TotalBarSalesRecievable { get; set; }
    
        public virtual Person Person { get; set; }
    }
}
