//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelMateWeb.Dal.DataCore
{
    using System;
    using System.Collections.Generic;
    
    public partial class Escort
    {
        public Escort()
        {
            this.EscortPictures = new HashSet<EscortPicture>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Telephone { get; set; }
        public string Mobile { get; set; }
        public string Description { get; set; }
        public string PicturePath { get; set; }
    
        public virtual ICollection<EscortPicture> EscortPictures { get; set; }
    }
}
