//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelMateWeb.Dal.DataCore
{
    using System;
    using System.Collections.Generic;
    
    public partial class GuestRequestItem
    {
        public int Id { get; set; }
        public int ItemId { get; set; }
        public int Quantity { get; set; }
        public decimal Price { get; set; }
        public bool Confirmed { get; set; }
        public bool Delivered { get; set; }
        public bool IsActive { get; set; }
        public bool Paid { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int GuestOrderId { get; set; }
        public string RequestBy { get; set; }
    
        public virtual GuestOrder GuestOrder { get; set; }
        public virtual StockItem StockItem { get; set; }
    }
}
