//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelMateWeb.Dal.DataCore
{
    using System;
    using System.Collections.Generic;
    
    public partial class Guest
    {
        public Guest()
        {
            this.GuestOrders = new HashSet<GuestOrder>();
            this.GuestReservations = new HashSet<GuestReservation>();
            this.GuestRooms = new HashSet<GuestRoom>();
            this.GuestPlaylists = new HashSet<GuestPlaylist>();
            this.RoomTransferHistories = new HashSet<RoomTransferHistory>();
            this.SoldItemsAlls = new HashSet<SoldItemsAll>();
            this.Transactions = new HashSet<Transaction>();
            this.GuestLedgers = new HashSet<GuestLedger>();
            this.GuestChats = new HashSet<GuestChat>();
            this.GuestChatMessages = new HashSet<GuestChatMessage>();
            this.GuestChatMessages1 = new HashSet<GuestChatMessage>();
            this.GuestFeedBacks = new HashSet<GuestFeedBack>();
            this.PaymentOrders = new HashSet<PaymentOrder>();
            this.BarTables = new HashSet<BarTable>();
            this.Payments = new HashSet<Payment>();
        }
    
        public int Id { get; set; }
        public string FullName { get; set; }
        public string Address { get; set; }
        public string Telephone { get; set; }
        public string Mobile { get; set; }
        public int CountryId { get; set; }
        public string CarDetails { get; set; }
        public string Status { get; set; }
        public string Notes { get; set; }
        public string Email { get; set; }
        public string PassportNumber { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public bool IsFutureReservation { get; set; }
        public int HotelId { get; set; }
        public Nullable<int> PersonId { get; set; }
        public string RoomNumber { get; set; }
        public Nullable<int> GuestRoomId { get; set; }
        public bool IsChild { get; set; }
        public bool IsPresent { get; set; }
    
        public virtual Hotel Hotel { get; set; }
        public virtual ICollection<GuestOrder> GuestOrders { get; set; }
        public virtual ICollection<GuestReservation> GuestReservations { get; set; }
        public virtual ICollection<GuestRoom> GuestRooms { get; set; }
        public virtual ICollection<GuestPlaylist> GuestPlaylists { get; set; }
        public virtual ICollection<RoomTransferHistory> RoomTransferHistories { get; set; }
        public virtual ICollection<SoldItemsAll> SoldItemsAlls { get; set; }
        public virtual ICollection<Transaction> Transactions { get; set; }
        public virtual ICollection<GuestLedger> GuestLedgers { get; set; }
        public virtual ICollection<GuestChat> GuestChats { get; set; }
        public virtual ICollection<GuestChatMessage> GuestChatMessages { get; set; }
        public virtual ICollection<GuestChatMessage> GuestChatMessages1 { get; set; }
        public virtual ICollection<GuestFeedBack> GuestFeedBacks { get; set; }
        public virtual ICollection<PaymentOrder> PaymentOrders { get; set; }
        public virtual ICollection<BarTable> BarTables { get; set; }
        public virtual ICollection<Payment> Payments { get; set; }
        public virtual Person Person { get; set; }
        public virtual BusinessAccount BusinessAccount { get; set; }
    }
}
