//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelMateWeb.Dal.DataCore
{
    using System;
    using System.Collections.Generic;
    
    public partial class GuestOrder
    {
        public GuestOrder()
        {
            this.GuestOrderItems = new HashSet<GuestOrderItem>();
            this.GuestBillItems = new HashSet<GuestBillItem>();
            this.GuestRequestItems = new HashSet<GuestRequestItem>();
            this.PaymentOrders = new HashSet<PaymentOrder>();
        }
    
        public int Id { get; set; }
        public int TableId { get; set; }
        public Nullable<int> PersonId { get; set; }
        public string Name { get; set; }
        public bool IsActive { get; set; }
        public bool Paid { get; set; }
        public int GuestId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public bool PreparedByWaitress { get; set; }
    
        public virtual ICollection<GuestOrderItem> GuestOrderItems { get; set; }
        public virtual Guest Guest { get; set; }
        public virtual ICollection<GuestBillItem> GuestBillItems { get; set; }
        public virtual ICollection<GuestRequestItem> GuestRequestItems { get; set; }
        public virtual ICollection<PaymentOrder> PaymentOrders { get; set; }
        public virtual BarTable BarTable { get; set; }
        public virtual Person Person { get; set; }
    }
}
