//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelMateWeb.Dal.DataCore
{
    using System;
    using System.Collections.Generic;
    
    public partial class GuestRoom
    {
        public GuestRoom()
        {
            this.GuestRoomAccounts = new HashSet<GuestRoomAccount>();
            this.BusinessAccounts = new HashSet<BusinessAccount>();
        }
    
        public int Id { get; set; }
        public int GuestId { get; set; }
        public int RoomId { get; set; }
        public System.DateTime CheckinDate { get; set; }
        public System.DateTime CheckoutDate { get; set; }
        public bool IsActive { get; set; }
        public string Notes { get; set; }
        public decimal RoomRate { get; set; }
        public int Occupants { get; set; }
        public int Children { get; set; }
        public bool GroupBooking { get; set; }
        public bool GroupBookingMainRoom { get; set; }
        public string RoomNumber { get; set; }
        public bool SameDayTransfer { get; set; }
    
        public virtual ICollection<GuestRoomAccount> GuestRoomAccounts { get; set; }
        public virtual Room Room { get; set; }
        public virtual Guest Guest { get; set; }
        public virtual ICollection<BusinessAccount> BusinessAccounts { get; set; }
    }
}
