//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelMateWeb.Dal.DataCore
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hotel
    {
        public Hotel()
        {
            this.Items = new HashSet<Item>();
            this.PersonTypes = new HashSet<PersonType>();
            this.Rooms = new HashSet<Room>();
            this.Guests = new HashSet<Guest>();
            this.BusinessAccounts = new HashSet<BusinessAccount>();
            this.StockItems = new HashSet<StockItem>();
            this.People = new HashSet<Person>();
        }
    
        public int Id { get; set; }
        public string HotelName { get; set; }
        public string Description { get; set; }
        public string Address { get; set; }
        public string Telephone { get; set; }
        public string ContactName { get; set; }
    
        public virtual ICollection<Item> Items { get; set; }
        public virtual ICollection<PersonType> PersonTypes { get; set; }
        public virtual ICollection<Room> Rooms { get; set; }
        public virtual ICollection<Guest> Guests { get; set; }
        public virtual ICollection<BusinessAccount> BusinessAccounts { get; set; }
        public virtual ICollection<StockItem> StockItems { get; set; }
        public virtual ICollection<Person> People { get; set; }
    }
}
