//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelMateWeb.Dal.DataCore
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        public int Id { get; set; }
        public int StatusType { get; set; }
        public int RaisedBy { get; set; }
        public int AssignedTo { get; set; }
        public Nullable<int> Supplier { get; set; }
        public decimal TotalAmount { get; set; }
        public System.DateTime InvoiceDate { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int PurchaseOrderId { get; set; }
    
        public virtual InvoiceStatusType InvoiceStatusType { get; set; }
        public virtual PurchaseOrder PurchaseOrder { get; set; }
        public virtual Person Person { get; set; }
        public virtual Person Person1 { get; set; }
    }
}
