//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelMateWeb.Dal.DataCore
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public Item()
        {
            this.Transactions = new HashSet<Transaction>();
        }
    
        public int Id { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public string Description { get; set; }
        public string Status { get; set; }
        public int Quantity { get; set; }
        public string Category { get; set; }
        public decimal OrigPrice { get; set; }
        public int NotNumber { get; set; }
        public string NotStatus { get; set; }
        public byte[] Picture { get; set; }
        public string ItemName { get; set; }
        public byte[] Checker { get; set; }
        public int TotalQuantity { get; set; }
        public string Barcode { get; set; }
        public string OrderStatus { get; set; }
        public string DISCOUNT { get; set; }
        public Nullable<System.DateTime> DISCOUNTSTARTDATE { get; set; }
        public Nullable<System.DateTime> DISCOUNTENDDATE { get; set; }
        public Nullable<decimal> DISCOUNTEDPERCENTAGE { get; set; }
        public string SubCategory { get; set; }
        public int HotelId { get; set; }
    
        public virtual Hotel Hotel { get; set; }
        public virtual Item Item1 { get; set; }
        public virtual Item Item2 { get; set; }
        public virtual ICollection<Transaction> Transactions { get; set; }
    }
}
