//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelMateWeb.Dal.DataCore
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentMethod
    {
        public PaymentMethod()
        {
            this.GuestRoomAccounts = new HashSet<GuestRoomAccount>();
            this.SoldItemsAlls = new HashSet<SoldItemsAll>();
            this.BusinessCorporateAccounts = new HashSet<BusinessCorporateAccount>();
            this.Payments = new HashSet<Payment>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ICollection<GuestRoomAccount> GuestRoomAccounts { get; set; }
        public virtual ICollection<SoldItemsAll> SoldItemsAlls { get; set; }
        public virtual ICollection<BusinessCorporateAccount> BusinessCorporateAccounts { get; set; }
        public virtual ICollection<Payment> Payments { get; set; }
    }
}
