//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelMateWeb.Dal.DataCore
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int Id { get; set; }
        public System.DateTime PaymentDate { get; set; }
        public int PaymentMethodId { get; set; }
        public decimal Total { get; set; }
        public decimal SubTotal { get; set; }
        public string Tax { get; set; }
        public decimal TaxAmount { get; set; }
        public string Discount { get; set; }
        public decimal DiscountAmount { get; set; }
        public string ServiceCharge { get; set; }
        public decimal ServiceChargeAmount { get; set; }
        public string Resident { get; set; }
        public decimal ResidentAmount { get; set; }
        public int CashierId { get; set; }
        public Nullable<int> GuestId { get; set; }
        public string Notes { get; set; }
        public string ReceiptNumber { get; set; }
        public decimal Paid { get; set; }
        public decimal Outstanding { get; set; }
        public int Type { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> DistributionPointId { get; set; }
        public Nullable<int> BusinessAccountId { get; set; }
        public int PaymentTypeId { get; set; }
    
        public virtual BusinessAccount BusinessAccount { get; set; }
        public virtual Guest Guest { get; set; }
        public virtual PaymentMethod PaymentMethod { get; set; }
        public virtual RoomPaymentType RoomPaymentType { get; set; }
        public virtual DistributionPoint DistributionPoint { get; set; }
        public virtual Person Person { get; set; }
    }
}
