//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelMateWeb.Dal.DataCore
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentOrder
    {
        public int Id { get; set; }
        public string Email { get; set; }
        public System.DateTime PaymentDate { get; set; }
        public string TransactionRef { get; set; }
        public string PaymentRef { get; set; }
        public string ResponseCode { get; set; }
        public bool TransactionStatus { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public int GuestId { get; set; }
        public int GuestOrderId { get; set; }
    
        public virtual Guest Guest { get; set; }
        public virtual GuestOrder GuestOrder { get; set; }
    }
}
