//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelMateWeb.Dal.DataCore
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonType
    {
        public PersonType()
        {
            this.People = new HashSet<Person>();
        }
    
        public int PersonTypeId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int HotelId { get; set; }
    
        public virtual Hotel Hotel { get; set; }
        public virtual ICollection<Person> People { get; set; }
    }
}
