//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelMateWeb.Dal.DataCore
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        public Person()
        {
            this.BarTables = new HashSet<BarTable>();
            this.BusinessCorporateAccounts = new HashSet<BusinessCorporateAccount>();
            this.DistributionPoints = new HashSet<DistributionPoint>();
            this.DistributionPointItems = new HashSet<DistributionPointItem>();
            this.EmployeeShifts = new HashSet<EmployeeShift>();
            this.Expenses = new HashSet<Expense>();
            this.Guests = new HashSet<Guest>();
            this.GuestCredentials = new HashSet<GuestCredential>();
            this.GuestLedgers = new HashSet<GuestLedger>();
            this.GuestOrders = new HashSet<GuestOrder>();
            this.GuestRoomAccounts = new HashSet<GuestRoomAccount>();
            this.Invoices = new HashSet<Invoice>();
            this.Invoices1 = new HashSet<Invoice>();
            this.Payments = new HashSet<Payment>();
            this.SalesDiscounts = new HashSet<SalesDiscount>();
            this.SoldItemsAlls = new HashSet<SoldItemsAll>();
            this.Stores = new HashSet<Store>();
            this.StoreItems = new HashSet<StoreItem>();
            this.StorePoints = new HashSet<StorePoint>();
            this.UsedItemsByHotels = new HashSet<UsedItemsByHotel>();
        }
    
        public int PersonID { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string Title { get; set; }
        public System.DateTime BirthDate { get; set; }
        public string Address { get; set; }
        public int HotelId { get; set; }
        public int PersonTypeId { get; set; }
        public string DisplayName { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string Guardian { get; set; }
        public string GuardianAddress { get; set; }
        public string PreviousEmployer { get; set; }
        public Nullable<System.DateTime> PreviousEmployerStartDate { get; set; }
        public Nullable<System.DateTime> PreviousEmployerEndDate { get; set; }
        public string ReasonForLeaving { get; set; }
        public string Notes { get; set; }
        public string Telephone { get; set; }
        public string Mobile { get; set; }
        public string JobTitle { get; set; }
        public string CityState { get; set; }
        public string WorkAddress { get; set; }
        public string MaritalStatus { get; set; }
        public string NoOfChildren { get; set; }
        public string PlaceOfBirth { get; set; }
        public string IdNumber { get; set; }
        public string BankDetails { get; set; }
        public string AccountNumber { get; set; }
        public Nullable<decimal> Salary { get; set; }
        public string Department { get; set; }
        public string Gender { get; set; }
        public string Qualification { get; set; }
        public string PicturePath { get; set; }
        public bool FullMember { get; set; }
        public Nullable<int> DistributionPointId { get; set; }
    
        public virtual ICollection<BarTable> BarTables { get; set; }
        public virtual ICollection<BusinessCorporateAccount> BusinessCorporateAccounts { get; set; }
        public virtual ICollection<DistributionPoint> DistributionPoints { get; set; }
        public virtual DistributionPoint DistributionPoint { get; set; }
        public virtual ICollection<DistributionPointItem> DistributionPointItems { get; set; }
        public virtual ICollection<EmployeeShift> EmployeeShifts { get; set; }
        public virtual ICollection<Expense> Expenses { get; set; }
        public virtual ICollection<Guest> Guests { get; set; }
        public virtual ICollection<GuestCredential> GuestCredentials { get; set; }
        public virtual ICollection<GuestLedger> GuestLedgers { get; set; }
        public virtual ICollection<GuestOrder> GuestOrders { get; set; }
        public virtual ICollection<GuestRoomAccount> GuestRoomAccounts { get; set; }
        public virtual Hotel Hotel { get; set; }
        public virtual ICollection<Invoice> Invoices { get; set; }
        public virtual ICollection<Invoice> Invoices1 { get; set; }
        public virtual ICollection<Payment> Payments { get; set; }
        public virtual PersonType PersonType { get; set; }
        public virtual ICollection<SalesDiscount> SalesDiscounts { get; set; }
        public virtual ICollection<SoldItemsAll> SoldItemsAlls { get; set; }
        public virtual ICollection<Store> Stores { get; set; }
        public virtual ICollection<StoreItem> StoreItems { get; set; }
        public virtual ICollection<StorePoint> StorePoints { get; set; }
        public virtual ICollection<UsedItemsByHotel> UsedItemsByHotels { get; set; }
    }
}
