//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelMateWeb.Dal.DataCore
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseOrderItem
    {
        public PurchaseOrderItem()
        {
            this.StorePointItems = new HashSet<StorePointItem>();
        }
    
        public int Id { get; set; }
        public int ItemId { get; set; }
        public int PurchaseOrderId { get; set; }
        public int Qty { get; set; }
        public decimal TotalPrice { get; set; }
        public int QtyRecieved { get; set; }
        public int Returns { get; set; }
        public decimal ReturnValue { get; set; }
    
        public virtual PurchaseOrder PurchaseOrder { get; set; }
        public virtual ICollection<StorePointItem> StorePointItems { get; set; }
        public virtual StockItem StockItem { get; set; }
    }
}
