//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelMateWeb.Dal.DataCore
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoomTransferHistory
    {
        public int Id { get; set; }
        public string Notes { get; set; }
        public int OldRoomId { get; set; }
        public int NewRoomId { get; set; }
        public int OldGuestId { get; set; }
        public int NewGuestId { get; set; }
        public System.DateTime TransferDate { get; set; }
        public bool IsActive { get; set; }
        public string OldRoomNumber { get; set; }
        public string OldGuestName { get; set; }
    
        public virtual Guest Guest { get; set; }
    }
}
