//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelMateWeb.Dal.DataCore
{
    using System;
    using System.Collections.Generic;
    
    public partial class Room
    {
        public Room()
        {
            this.GuestReservations = new HashSet<GuestReservation>();
            this.GuestRooms = new HashSet<GuestRoom>();
            this.Picturals = new HashSet<Pictural>();
        }
    
        public int Id { get; set; }
        public string RoomNumber { get; set; }
        public int NoOfBeds { get; set; }
        public int StatusId { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string Smoking { get; set; }
        public int RoomType { get; set; }
        public string ExtNumber { get; set; }
        public string Notes { get; set; }
        public bool IsActive { get; set; }
        public Nullable<decimal> BusinessPrice { get; set; }
        public int HotelId { get; set; }
        public string Description { get; set; }
        public byte[] RowVersion { get; set; }
    
        public virtual ICollection<GuestReservation> GuestReservations { get; set; }
        public virtual ICollection<GuestRoom> GuestRooms { get; set; }
        public virtual Hotel Hotel { get; set; }
        public virtual RoomStatu RoomStatu { get; set; }
        public virtual RoomType RoomType1 { get; set; }
        public virtual ICollection<Pictural> Picturals { get; set; }
    }
}
