//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelMateWeb.Dal.DataCore
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesDiscount
    {
        public int Id { get; set; }
        public System.DateTime DiscountDate { get; set; }
        public string ReceiptNumber { get; set; }
        public decimal Amount { get; set; }
        public int PersonId { get; set; }
        public int ActualCashierId { get; set; }
    
        public virtual Person Person { get; set; }
    }
}
