//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelMateWeb.Dal.DataCore
{
    using System;
    using System.Collections.Generic;
    
    public partial class SoldItemsAll
    {
        public int Id { get; set; }
        public int ItemId { get; set; }
        public int Qty { get; set; }
        public decimal TotalPrice { get; set; }
        public int TransactionId { get; set; }
        public Nullable<System.DateTime> DateSold { get; set; }
        public bool IsActive { get; set; }
        public int PersonId { get; set; }
        public bool TillOpen { get; set; }
        public Nullable<int> PaymentTypeId { get; set; }
        public Nullable<int> GuestId { get; set; }
        public int PaymentMethodId { get; set; }
        public string PaymentMethodNote { get; set; }
        public System.DateTime TimeOfSale { get; set; }
        public int DistributionPointId { get; set; }
        public Nullable<int> BusinessAccountId { get; set; }
        public string RecieptNumber { get; set; }
        public string ReasonForVoid { get; set; }
    
        public virtual Guest Guest { get; set; }
        public virtual PaymentMethod PaymentMethod { get; set; }
        public virtual StockItem StockItem { get; set; }
        public virtual BusinessAccount BusinessAccount { get; set; }
        public virtual DistributionPoint DistributionPoint { get; set; }
        public virtual Person Person { get; set; }
    }
}
