//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelMateWeb.Dal.DataCore
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockItem
    {
        public StockItem()
        {
            this.Batches = new HashSet<Batch>();
            this.DamagedBatchItems = new HashSet<DamagedBatchItem>();
            this.DistributionPointItems = new HashSet<DistributionPointItem>();
            this.FoodMatrices = new HashSet<FoodMatrix>();
            this.FoodMatrices1 = new HashSet<FoodMatrix>();
            this.GuestBillItems = new HashSet<GuestBillItem>();
            this.GuestOrderItems = new HashSet<GuestOrderItem>();
            this.GuestRequestItems = new HashSet<GuestRequestItem>();
            this.POSItems = new HashSet<POSItem>();
            this.PurchaseOrderItems = new HashSet<PurchaseOrderItem>();
            this.SoldItemsAlls = new HashSet<SoldItemsAll>();
            this.TableItems = new HashSet<TableItem>();
            this.UsedItemsByHotels = new HashSet<UsedItemsByHotel>();
        }
    
        public int Id { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public string Description { get; set; }
        public string PicturePath { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string Status { get; set; }
        public int Quantity { get; set; }
        public int CategoryId { get; set; }
        public decimal OrigPrice { get; set; }
        public int NotNumber { get; set; }
        public string NotStatus { get; set; }
        public string StockItemName { get; set; }
        public byte[] Checker { get; set; }
        public int TotalQuantity { get; set; }
        public string Barcode { get; set; }
        public string OrderStatus { get; set; }
        public string DISCOUNT { get; set; }
        public Nullable<System.DateTime> DISCOUNTSTARTDATE { get; set; }
        public Nullable<System.DateTime> DISCOUNTENDDATE { get; set; }
        public Nullable<decimal> DISCOUNTEDPERCENTAGE { get; set; }
        public int HotelId { get; set; }
        public bool ForSale { get; set; }
        public bool CookedFood { get; set; }
        public bool KitchenOnly { get; set; }
        public bool Discounted { get; set; }
        public bool RawItem { get; set; }
        public bool StarBuy { get; set; }
        public Nullable<decimal> ClubPrice { get; set; }
    
        public virtual ICollection<Batch> Batches { get; set; }
        public virtual ICollection<DamagedBatchItem> DamagedBatchItems { get; set; }
        public virtual ICollection<DistributionPointItem> DistributionPointItems { get; set; }
        public virtual ICollection<FoodMatrix> FoodMatrices { get; set; }
        public virtual ICollection<FoodMatrix> FoodMatrices1 { get; set; }
        public virtual ICollection<GuestBillItem> GuestBillItems { get; set; }
        public virtual ICollection<GuestOrderItem> GuestOrderItems { get; set; }
        public virtual ICollection<GuestRequestItem> GuestRequestItems { get; set; }
        public virtual Hotel Hotel { get; set; }
        public virtual ICollection<POSItem> POSItems { get; set; }
        public virtual ICollection<PurchaseOrderItem> PurchaseOrderItems { get; set; }
        public virtual ICollection<SoldItemsAll> SoldItemsAlls { get; set; }
        public virtual StockItem StockItem1 { get; set; }
        public virtual StockItem StockItem2 { get; set; }
        public virtual ICollection<TableItem> TableItems { get; set; }
        public virtual ICollection<UsedItemsByHotel> UsedItemsByHotels { get; set; }
    }
}
