//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelMateWeb.Dal.DataCore
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supplier
    {
        public int SupplierID { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string Title { get; set; }
        public System.DateTime BirthDate { get; set; }
        public string Address { get; set; }
        public int HotelId { get; set; }
        public int SupplierTypeId { get; set; }
        public string DisplayName { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string Guardian { get; set; }
        public string GuardianAddress { get; set; }
        public string PreviousEmployer { get; set; }
        public Nullable<System.DateTime> PreviousEmployerStartDate { get; set; }
        public Nullable<System.DateTime> PreviousEmployerEndDate { get; set; }
        public string ReasonForLeaving { get; set; }
        public string Notes { get; set; }
    }
}
