//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelMateWeb.Dal.DataCore
{
    using System;
    using System.Collections.Generic;
    
    public partial class TableItem
    {
        public int Id { get; set; }
        public int TableId { get; set; }
        public int ItemId { get; set; }
        public int Qty { get; set; }
        public System.DateTime DateSold { get; set; }
        public int Cashier { get; set; }
        public Nullable<int> GuestOrderItemId { get; set; }
        public bool Fulfilled { get; set; }
        public bool Collected { get; set; }
        public Nullable<System.DateTime> CompletedTime { get; set; }
        public Nullable<System.DateTime> CollectedTime { get; set; }
        public bool Completed { get; set; }
        public bool StoreFulfilled { get; set; }
        public Nullable<System.DateTime> StoreFulfilledTime { get; set; }
        public bool SentToPOS { get; set; }
        public string Note { get; set; }
        public bool IsActive { get; set; }
        public bool SentToPrinter { get; set; }
    
        public virtual BarTable BarTable { get; set; }
        public virtual StockItem StockItem { get; set; }
    }
}
