//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelMateWeb.Dal.DataCore
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public Transaction()
        {
            this.Items = new HashSet<Item>();
        }
    
        public int Id { get; set; }
        public System.DateTime TranscationDate { get; set; }
        public bool IsActive { get; set; }
        public decimal Amount { get; set; }
        public int StaffId { get; set; }
        public string GuestSignature { get; set; }
        public int GuestId { get; set; }
    
        public virtual ICollection<Item> Items { get; set; }
        public virtual Guest Guest { get; set; }
    }
}
